scope: mx
name: postgresql1
restapi:
  listen: 127.0.0.1:8009
  connect_address: 127.0.0.1:8009
consul:
  host: 127.0.0.1:8500
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
      - encoding: UTF8
      - data-checksums
      - host replication replicator 127.0.0.1/32 md5
      - host all all 127.0.0.1/32 trust
      - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: 127.0.0.1:9432
  connect_address: 127.0.0.1:9432
  data_dir: /tmp/postgresql1
  pgpass: /tmp/pgpass1
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
  parameters:
    unix_socket_directories: '.'
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
